# Generated by Django 5.1.2 on 2024-10-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(default='profile.jpg', upload_to='image/')),
            ],
            options={
                'db_table': 'bookadd',
            },
        ),
    ]
