# Generated by Django 5.1 on 2024-08-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Employees',
                'verbose_name_plural': 'Employees',
                'db_table': 'Employees',
            },
        ),
    ]
